### ISSUE TITLE
Billing Limit Reached

### ISSUE THREAD

**Issue by jacks0n9** [paschalc24/evil-gpt#1]
On your website, the billing limit has been reached for the openai api. I, however, recommend that you don't put your api key on a public website, just a really stupid idea. Someone could definitely take advantage of that. _Cough cough_ me. Anyways, fix it or don't

**Comment by jacks0n9** [comment]
Hmm, looks like the key has been invalidated. Did you do that? I know that it was definitely saying that the limit was reached just a few minutes ago

**Comment by paschalc24** [comment]
I did, thanks for the input.
